### ISSUE TITLE
希望能加入尾刀计算一栏

### ISSUE THREAD

**Issue by Asakawasennaci** [cutecutecat/KnightReport#2]
首先谢谢作者，这工具非常好用。建议新增尾刀次数，bigfun百宝袋会把尾刀标红，尾刀次数也是计算工会成员最终伤害的一个重要参数

**Comment by cutecutecat** [comment]
很有价值的建议，让我构思下怎么组织这部分结构，近期会加上

**Comment by cutecutecat** [comment]
v0.1.2已经部署了尾刀相关统计

**Comment by Asakawasennaci** [comment]
试用了一下，和之前版本没有新增东西，会不会传错包了

**Comment by Asakawasennaci** [comment]
> v0.1.2已经部署了尾刀相关统计
试用了一下，和之前版本没有新增东西，会不会传错包了

**Comment by cutecutecat** [comment]
自动打包好像出了点问题，我检查一下~

**Comment by cutecutecat** [comment]
应该处理好了，你再看看

**Comment by Asakawasennaci** [comment]
> 应该处理好了，你再看看

不行，显示0.12版本，但无新增功能

**Comment by Asakawasennaci** [comment]
> 应该处理好了，你再看看
可以了，有0.1.2的版本功能了。另外需要注意两个点，1、升级到0.1.2的时候我这需要重新登录网页百宝袋。2、bigfun的下载直链有二段显示，第一段是已经替换成0.1.2，但第二段还是0.1.1
