### ISSUE TITLE
生成文件失败

### ISSUE THREAD

**Issue by wheatmai** [cutecutecat/KnightReport#4]
win10 64位，edge浏览器。看log像是成功下载了，但未生成csv文件

[KnightReport.log](https://github.com/cutecutecat/KnightReport/files/7125355/KnightReport.log)
[KnightReport.err.log](https://github.com/cutecutecat/KnightReport/files/7125357/KnightReport.err.log)

![image](https://user-images.githubusercontent.com/44692904/132437740-334d2303-43a1-495b-974b-51762de48319.png)

**Comment by cutecutecat** [comment]
这个问题在上一次修复中被部分解决，详情可以参考#3

可以尝试下载最新的v0.1.1版本看是否还会出现
