### ISSUE TITLE
unhandled Exception   打不开

### ISSUE THREAD

**Issue by Chiayue** [cutecutecat/KnightReport#7]
![image](https://user-images.githubusercontent.com/41291438/134666753-0e9d28e0-6ae8-48ff-afdd-717d01195cb0.png)

failed to find Edge Exception

**Comment by cutecutecat** [comment]
目前初步认为是Edge版本号不匹配，导致browser_cookies无法从正确的地方找到cookies。

接下来的计划中，会改用自带浏览器的方案，不再依赖Edge等已安装浏览器。

**Comment by cutecutecat** [comment]
已更新版本，请参考[从文件输入cookies](doc/file-cookies.md)
