### ISSUE TITLE
MacOS 运行源码报错 ImportError: cannot import name set_start_method

### ISSUE THREAD

**Issue by w006gy** [cutecutecat/KnightReport#9]
Traceback (most recent call last):
  File "../src/main.py", line 6, in <module>
    from multiprocessing import Process, set_start_method, Queue, freeze_support, active_children, parent_process
ImportError: cannot import name set_start_method

**Comment by cutecutecat** [comment]
最近事情太多了，还没有做MacOS的支持，本来计划国庆做的，可能还得拖一拖啦(咕咕咕

0.1.2之后新的版本主要改变是自带了一个建议浏览器，不再需要依赖Edge了，但是作为代价，打包的可执行文件会膨胀到大约80M-100M，并且这部分还有很多bug，可以先用着0.1.2版本。

**Comment by cutecutecat** [comment]
现已支持MacOS可执行文件
